### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by Dashadower** [hyunjimoon/SBC#11]
Hierarchical spline takes around <40 minutes for "just" prior predictive sampling; probably due to process instantiation and IO.
Maybe for longer tasks(sampling), we can run multiple stan programs at once or use internal/write TBB or OpenMP interface to speed up batch sampling.

**Comment by hyunjimoon** [comment]
Would this parallel API help fitting in SBC? @Dashadower 
https://github.com/stan-dev/design-docs/pull/40#issue-610201560
