### ISSUE TITLE
calculate_rank does not handle discrete parameters correctly

### ISSUE THREAD

**Issue by martinmodrak** [hyunjimoon/SBC#16]
SBC also works with discrete unobserved parameters. In fact, I've found SBC crucial intesting whether my implementation of marginalization for those parameters worked. However, the ranks will have ties in this case. In my implementation, I did preserve the uniformness of the posterior ranks by randomizing across the ties (as `rank(..., ties.method = "random")` does). Maybe there are other ways, but this one seems to work.

Will build an example with discrete parameters and test this.

**Comment by hyunjimoon** [comment]
Theories on rank ties are documented in [this](https://github.com/hyunjimoon/SBC/wiki/SBC-FAQ#rank-smoothing) wiki and I believe this issue has been implemented. Could you confirm and close this issue? @martinmodrak

**Comment by martinmodrak** [comment]
Correct,  this implemented in the current version
