### ISSUE TITLE
combine_args and custom_SBC_generator

### ISSUE THREAD

**Issue by hyunjimoon** [hyunjimoon/SBC#22]
Is custom_SBC_generator function (generator$f from below) compatible with the following input?
```
do.call(generator$f, combine_args(generator$args, list(n_datasets = n_datasets)))
```
```
> combine_args(args, list(n_datasets = n_datasets))
[[1]]
[1] 1

...

[[9]]
[1] 9

[[10]]
[1] 10

$n_datasets
[1] 10
```
arg was `list(seq(1:10))`

**Comment by hyunjimoon** [comment]
For `combine_args` in utils.R, why would you want to "overwrite elements with the same name using the value from args2"? @martinmodrak

**Comment by martinmodrak** [comment]
> Is custom_SBC_generator function (generator$f from below) compatible with the following input?

I don't think I fully understand what are you trying to do. In any case, in almost all places, where you can use `custom_SBC_generator`, you can also just create a dataset by preparing your data and calling `SBC_datasets`. To be specific running:

```r
gen <- custom_SBC_generator(f, <<some other args>>)
datasets <- generate_datasets(gen, n_datasets = 30)
```

should be equivalent to just running

```r
datasets <- f(<<some other args>>, n_datasets = 30)
```

 `custom_SBC_generator` IMHO only makes sense for people developing some abstraction over the SBC package and when using the (currently not yet implemented) workflow/steward class.

> For combine_args in utils.R, why would you want to "overwrite elements with the same name using the value from args2"?

When using `combine_args` I usually know which set of arguments should take precedence the current use cases are arguments need to be controlled by the SBC package (e.g. setting the number of cores to use) and the combination of `brms_SBC_generator` and `brms_SBC_backend_from_generator` where you may want the actual SBC fits to use somewhat different settings than what you used for generating data (in my current tests, this was quite useful for the number of warmup iterations and thinning which may need to be higher when sampling just from the prior). 

> Could I ask the purpose for storing N for every simulated datasets?

SBC package has no opinion on how you should write your Stan code, so it makes no assumptions. As far as the SBC package is concerned, the `$generated` elements are black boxes. Different backends may require different format of datasets. Even when looking only at Stan models, a model doesn't even have to define `N` as a data input. Additionally, if one wants to test a model in a setting where the size of the dataset is not known beforehand, one can plausibly want to run SBC while varying the number of observations between datasets.

**Comment by hyunjimoon** [comment]
Example of `custom_nprior` is implemented in [here](https://github.com/hyunjimoon/defense-reliability/blob/workflow/R/2_Theta_bar_Y/DtrMngSep/DMSep_SBC.R). @martinmodrak Could you please check whether the code follows your design intention?

**Comment by martinmodrak** [comment]
Yes, that is what I had in mind.
