### ISSUE TITLE
lp__ calculation for (nonbrms) stan model

### ISSUE THREAD

**Issue by hyunjimoon** [hyunjimoon/SBC#26]
`lp__` is the most robust metric for SBC rank score. Insert `lp__` calculation in the generator function.

**Comment by martinmodrak** [comment]
Just added a (somewhat under-documented and under-tested) feature to define custom generated quantities in R. Those are evaluated in the same way for both prior and posterior samples and can thus be used for SBC. An example using this to include the log-likehood in models is given in the `limits_of_SBC.Rmd` vignette and also added to the `brms` vignette.
