### ISSUE TITLE
Vignette on adding new backends

### ISSUE THREAD

**Issue by martinmodrak** [hyunjimoon/SBC#37]
We also might want to have backends be able to influence the default thinning (e.g. for ADVI/optimizing fits it makes no sense to thin as the samples from the approximate posterior are already independent)

A good example could be treating the default `lm` or `glm` methods in R as approximation to Bayesian models and see under which circumstances they are (mis)calibrated.

**Comment by hyunjimoon** [comment]
> samples from the approximate posterior are already independent
Would there be any reason to believe variational inference produces independent samples? Fig.3 from [this](https://papers.nips.cc/paper/2020/file/7cac11e2f46ed46c339ec3d569853759-Paper.pdf) paper shows autocorrelation and algorithm 1 includes ESS computation.

**Comment by martinmodrak** [comment]
From reading the code and docs, I think, the current implementation in Stan does that. The output contains a single mean vector which is presumable the mean of the Gaussian used to approximate the posterior. Additionally, the code does i.i.d. normal sampling (the code is at https://github.com/stan-dev/stan/blob/7b291dac8d7c9509bf11db540f5efde7a649d410/src/stan/variational/base_family.hpp#L56). I don't think I understand the paper you linked very well, but it seems to me that they measure autocorrelation and ESS for their estimates of the variational parameters, but then use a single estimate of the mean and covariance matrix to build the approximation. Also I don't think that they describe an algorithm that is currently implemented in Stan.

**Comment by hyunjimoon** [comment]
Regarding what Aki mentioned on importance resampling for debias purpose; as it is not implemented in the current stan version, so I guess it's ok to assume iid sampling?
