### ISSUE TITLE
SBC_generator_brms fails with `family = bernoulli`

### ISSUE THREAD

**Issue by martinmodrak** [hyunjimoon/SBC#48]

**Comment by bmfazio** [comment]
FYI this seems to be a problem with `brms` itself and failure only seems to occur in the case when `template_data` has all zeros in the outcome. I have reported it [here](https://github.com/paul-buerkner/brms/issues/1511). In the meantime, using a mixture of values or even just ones seems to let everything proceed without issue.

**Comment by martinmodrak** [comment]
Thanks very much for investigating! Appears resolved in latest brms, closing.
