### ISSUE TITLE
generate_datasets with brms errors out with constant priors or small n_sims

### ISSUE THREAD

**Issue by bmfazio** [hyunjimoon/SBC#77]
Using brms and specifying a constant prior on some parameter or using a small n_sims in `generate_datasets` will interrupt execution with an error due seemingly due to lack of NA handling in the if statements for Rhat/ESS warning ([reference](https://github.com/hyunjimoon/SBC/blob/1c5638d008f46968d3c964c6283326002a6905b8/R/datasets.R#L321)).

**Comment by martinmodrak** [comment]
Thanks for reporting, just tried a fix that works for a simple setup I tested. Would be great if you could check that the latest GitHub version also works for you.

My setup that broke previously and now works:

```r
template_data = data.frame(y = rep(0, 15), x = rnorm(15))
priors <- prior(normal(0,1), class = "b") +
    prior(constant(0), class = "Intercept") +
    prior(normal(0,1), class = "sigma")
generator <- SBC_generator_brms(y ~ x, data = template_data, prior = priors, 
                                thin = 50, warmup = 100, refresh = 2000)
ds <- generate_datasets(generator, 1)
```

**Comment by bmfazio** [comment]
My use case was quite similar to your example and it's working now, thanks!
