### ISSUE TITLE
NA's and varying max_rank in SBC_results object

### ISSUE THREAD

**Issue by IreneSophia** [hyunjimoon/SBC#85]
Hello, 

I want to use the SBC package to evaluate a brms model. The generator has the following specifications: 
```
gen = SBC_generator_brms(
          rt ~ group * condition + (condition | subject) + (condition * group | stimulus), 
          data = df, prior = priors, 
          warmup = 2000, iter = 4000, thin = 16, 
          generate_lp = TRUE, family = lognormal)
```
Group has three levels and condition has two, there are 70 subjects and 36 stimuli. 

I am running into a few problems. Already when running `generate_datasets` to create 1000 datasets, I receive the following message: 
```
Some rhats / bulk effective sample sizes are NA.
This is not a problem if you have constant elements in your model or you generated very few datasets and/or used little thinning.
```
I have tried to increase `thin` and `warmup` considerably, but I still get this message with 100,000 warmup, 200,000 iterations and 128 thinning. It goes away if I remove the slopes from subject and stimulus entirely (`rt ~ group * condition + (1 | subject) + (1 | stimulus)`), as soon as there is one slope I get the `NA` warning. 

Therefore, I went ahead with the original formula including the slopes for subject and stimulus to see what other issues come up, using the following code: 
```
back = SBC_backend_brms_from_generator(gen)
results = compute_SBC(data, back,
         cache_mode = "results", 
         cache_location = file.path(cache_dir, "results_1000"))
```
I get quite a lot of warnings when running this: 
```
 - 1000 (100%) fits had at least one Rhat > 1.01. Largest Rhat was NA.
 - 1000 (100%) fits had tail ESS undefined or less than half of the maximum rank, potentially skewing 
the rank statistics. The lowest tail ESS was NA.
 If the fits look good otherwise, increasing `thin_ranks` (via recompute_SBC_statistics) 
or number of posterior draws (by refitting) might help.
 - 121 (12%) fits had iterations that saturated max treedepth. Maximum number of max treedepth was 500.
 - 1000 (100%) fits had some steps rejected. Maximum number of rejections was 48.
Not all diagnostics are OK.
You can learn more by inspecting $default_diagnostics, $backend_diagnostics 
and/or investigating $outputs/$messages/$warnings for detailed output from the backend.
Warning messages:
1: In check_stats(stats, datasets, thin_ranks = thin_ranks, ensure_num_ranks_divisor = ensure_num_ranks_divisor,  :
  Differening max_rank across fits
2: In check_stats(stats, datasets, thin_ranks = thin_ranks, ensure_num_ranks_divisor = ensure_num_ranks_divisor,  :
  Ranks were computed from fewer than 50 samples, the SBC checks will have low precision.
You may need to increase the number of samples from the backend and make sure that the combination of thinning in the backend, `thin_ranks` and `ensure_num_ranks_divisor` is sensible.
Currently thin_ranks = 10, ensure_num_ranks_divisor = 2.
```

My model doesn't seem overly complex to me, and if I ignore the NAs and the instances where max_rank is smaller than 51, the `plot_ecdf_diff` and `plot_rank_hist` look fine but not perfect. Although there are rhats that are larger, the 3rd quantile is 1.005, so the majority look good. 

Does anyone have any ideas what the problem is and how I could tweak my model to improve it? 

Here's some info on my system:
```
x86_64-pc-linux-gnu 
R version 4.3.1 (2023-06-16)
RStudio 2023.09.1+494
brms 2.20.4
SBC 0.2.0.9000
cmdstanr 0.6.1
```

**Comment by lunafazio** [comment]
> NAs typically result when the parameter value is exactly identical in all draws.

I think this is indeed the case, [did a quick simulation](https://gist.github.com/lunafazio/28817752b372a2b90a11e198c6966110) and found some all-one/zero values from the correlation and Cholesky factor matrices showing up in the `$variables` matrix of draws.

**Comment by IreneSophia** [comment]
Thank you both for your fast replies and efforts. I also checked the NAs in my simulations and it's the same variables as you found, so this explains them. 

Concerning the different `max_rank`, however, it seems that there are certain simulations where the `max_rank` is different (either 39 or 25) from the rest of the simulations (51). Although some of these have low `ess_bulk` and `ess_tail` and/or high `rhats`, most them look fine apart from the `max_rank`. Any idea about the cause of that?

**Comment by martinmodrak** [comment]
First guess would be that, this corresponds to some chains failing for those simulations - you should be able to check `results$backend_diagnostics` and `results$outputs` (or maybe `results$warnings` and `results$errors`) for some more info. Chains could for example fail, if they fail to initialize. It might be the case that some of the simulated datasets are problematic and unrealistic - if the unfinished chains correspond to only such weird datasets, it is safe to just remove them (preferably before computing the results).

Also max_rank of 51 is pretty small - if that was not set on purpose for faster testing, you probably want more posterior iterations (or less aggressive thinning if your ESSs are actually quite good).

**Comment by IreneSophia** [comment]
I reran everything with more posterior iterations which solved the `max_rank` issue. The NAs were still confined to irrelevant variables, so this answers both of my questions. 

Thanks!
