### ISSUE TITLE
Option for plotting grouped parameters?

### ISSUE THREAD

**Issue by bmfazio** [hyunjimoon/SBC#88]
I have a model with multiple parameters that play a similar role, so looking at them in a single plot feels just as effective and results in a more compact visualisation. Since some facets may have more parameters than others, I scale down the alpha to try and keep the visual balance.

Below is an example I quickly hacked together. If this seems like a desirable feature, I could try to make a proper implementation for both ecdf plots (not sure how it would work out with the other types of plots).

![image](https://github.com/hyunjimoon/SBC/assets/26548493/87664d97-5002-4e19-bee2-61bc31d6e641)

**Comment by martinmodrak** [comment]
Sorry for missing this initially. Yes, that would be great! I think a sensible API would be to add a `combine` argument to the plots which would be either `NULL` (default) or a `list` of the form:

```R
list(display_name = c("items", "to", "combine")
```

We then might (or might not) add some helper build a function that builds this list automatically to collapse arrays.

Would also make sense to add a `combine_alpha` argument to add transparency to the combined plots.
