### ISSUE TITLE
Implement new plots from Aki Vehtari's new paper

### ISSUE THREAD

**Issue by Dashadower** [hyunjimoon/SBC#9]
Throw this out: https://github.com/hyunjimoon/SBC/blob/b36038081dfd25ec3ae71a5abc00a9055d23445b/R/plot.R#L35
and add stuff from https://arxiv.org/abs/2103.10522

**Comment by Dashadower** [comment]
**Other plots and measures might need adjustments to keep it up to date

**Comment by martinmodrak** [comment]
Not sure if this is the right place to comment, but I think Aki wanted to have the plots implemented in bayesplot at some point (hopefully soon), so it might be sensible to either wait until they get there or collaborate to have those plots in bayesplot sooner and avoid duplicating the code in this package.
