### ISSUE TITLE
compute_SBC using GPU / openCL?

### ISSUE THREAD

**Issue by abhsarma** [hyunjimoon/SBC#97]
This is more of a question than an issue / bug, but please feel free to move this to a discussion. I am trying to use SBC on a model which takes quite a long time to run (~2-3 mins on an M-based Macs). I am importing the model using cmdstan and specifying that I want to use `opencl`:

```r
mixture_bernoulli = cmdstan_model("model.stan", cpp_options = list(stan_opencl = TRUE))
```

When I run the model with the following command, it takes about ~20ish mins. If I run it on `rstan` (i.e. `mixture_bernoulli = rstan::stan_model("model.stan")`) and without the argument `opencl_ids = c(0, 2)`, it takes considerably longer. Does this mean that it is being computed on a GPU instead of the CPU, and the speedup is due to the greater number of GPU cores available? As far as I can tell, SBC is using `future` to parallelise computation, and while I am not very familiar with future, I think it does not parallelize over GPU cores.

```r
backend = SBC_backend_cmdstan_sample(mixture_bernoulli, opencl_ids = c(0, 2))
ds = generate_datasets(gen, n_sims = 20)
results = compute_SBC(ds, backend)
```

Could you provide any insight into this? Thanks!

**Comment by abhsarma** [comment]
Apologies---it seems I did research this properly as it turns out Apple no longer provides openCL support on the silicon based chips. I guess the issue is rather to do with rstan vs cmdstanr.

**Comment by martinmodrak** [comment]
No worries. I'll also add that SBC doesn't see within "backends" (model + algorithm) and will only ever paralellize by running multiple fits in parallel (which in turn may gain multiple cores per fit to sample multiple chains in parallel). The support for OpenCL in Stan allows for paralellization _within_ each chain. Effectively combining paralellization of multiple fits/chains over CPUs with within-chain paralellization on the GPU is a non-trivial undertaking and will require some benchmarking effort (e.g. the GPU may increase the speed when running 4 chains in parallel, but may reach its capacity and become the bottleneck when running 8 chains in parallel and thus you may have situtations when for "normal" use you benefit from the GPU while running SBC is faster without GPU)

Best of luck getting SBC running nicely for your model!

**Comment by abhsarma** [comment]
I was not aware of that. Thank you for the explanation! and thank you for creating this great package :)
