### ISSUE TITLE
Using SBC with generated quantities

### ISSUE THREAD

**Issue by mhollanders** [hyunjimoon/SBC#99]
Hi,

Perhaps a simple question, but is it possible to do SBC using generated quantities? My specific use case is where I'm doing SEM with sign-flipping in the generated quantities and would like to compare those variables of the same name with those supplied by `variables` in the generator function. 

Thanks!

Matt

**Comment by martinmodrak** [comment]
I think this should work out of the box - SBC only ever looks at the results of `posterior::as_draws_matrix(fit)`, which includes the generated quantities, so if this matches the simulator names there should be nor problem.

**Comment by mhollanders** [comment]
Thanks Martin. Turns I was confused due to the other issue I opened. I thought it wasn't accessing generated quantities, which it was, but it was struggling with indices due to the optional variables. My apologies.
